### ISSUE TITLE
Find datasets relating to social housing

### ISSUE THREAD

**Issue by ahussain3** [ahussain3/maya#1]
Anything and everything for now. We should try to get a sense of what we think is possible

**Comment by ahussain3** [comment]
https://visual.ons.gov.uk/ is a cool place to look

**Comment by initioterum** [comment]
Basic trends from the above link: https://visual.ons.gov.uk/social-housing-affordability/

Council housing policy: https://www.gov.uk/council-housing

Govt tables on various aspects of social housing: https://www.gov.uk/government/statistical-data-sets/live-tables-on-rents-lettings-and-tenancies
Table 600 (households on waiting lists, by district) is very revealing. I'm especially interested in how Milton Keynes has got 0 households on the waiting list since 2008, apparently. Finding data on the number of empty council houses would make an interesting comparison.

**Comment by initioterum** [comment]
Dept for Communities and Local Government has some of its data accessible by an API! http://opendatacommunities.org/def/concept/folders/themes/housing-market It'd be really cool to work this into the essay such that the data would continue to update (perhaps we'd need to mark when the essay was written somehow for posterity)

**Comment by initioterum** [comment]
DCLG Live Table 615 should have some useful data in it on vacant council stock (I've only had a quick look)
